server {
    server_name core-user-api.api.aitrade.ai core-user-api-local.api.aitrade.ai core-user-api-develop.api.aitrade.ai core-user-api-staging.api.aitrade.ai;
    listen      80;
    root        /var/www/html/core-user-api.api.aitrade.ai/public;
    index       index.php index.html index.htm;
    access_log  /var/log/nginx/core-user-api.api.aitrade.ai.log.access;
    error_log   /var/log/nginx/core-user-api.api.aitrade.ai.log.error notice;

    location ^~ /static/ {
    }

    add_header Content-Security-Policy upgrade-insecure-requests;
    try_files $uri /index.php$is_args$args;

    location ~ \.php$ {
        server_tokens off;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;

        fastcgi_pass api.app:9000;
        fastcgi_index index.php;
        fastcgi_read_timeout 30;

        include fastcgi_params;
    }
}